### ISSUE TITLE
Make trees work as background entities

### ISSUE THREAD

**Issue by powerkiddd** [powerkiddd/Tools#5]
Currently, you can't walk past trees and you have to jump over them.
I want them to sit in the background via another collision method to be able to still interact, but ignore player collision.

**Comment by Menleader** [comment]
But then the fact of jumping on them goes away. And what about other blocks are you abl eto jump these then?

**Comment by powerkiddd** [comment]
@Menleader You will no longer be able to jump on the trees because you will walk past them.
All other blocks in the game still have normal collision so you can still jump on them.
However, you won't be able to place a block at a place a tree is standing, you will have to cut down the tree first.
